### PR TITLE
created Invasion Forces, Star Destroyer, and Storm Troopers classes, …

### PR DESCRIPTION
**Pull request by MehmetArkun**
…with the former being the parent class of the rest.

Also created EmpireStrikesBack class to proceed with the code via main method. Also did some minor changes in Alien Invasion class.

### CODE REVIEW

**Review by Haden-Z — APPROVED** [review]
May the force be with you

**Comment by MehmetArkun** [comment]
> May the force be with you

May the Java be with you.

**Comment by ecaliskanunal** [comment]
Definitely solid work!

**Review by ecaliskanunal — APPROVED** [review]
Definitely solid work!

**Review by brunolena007 — COMMENTED** [review]
can you add a method for the allien atack!

**Comment by MehmetArkun** [comment]
> can you add a method for the allien atack!

will do!

**Review by akiftunc76 — COMMENTED** [review]
Amazing work!

**Comment by akiftunc76** [comment]
Well done!

**Pull request merged**
